### ISSUE TITLE
`proxyTypes` in README doesn't exist in repo

### ISSUE THREAD

**Issue by emarcotte** [apigee/apigee-templater#1]
Was just learning about how this module could be used in my own tools and saw the example in the readme has:

```
let input: ApigeeTemplateInput = {
  name: "MyProxy",
  type: proxyTypes.programmable,
...
```

Looking thru this repo I dont see that type defined anywhere. Is that something that should be removed?

**Comment by tyayers** [comment]
Yes true, removed that parameter since it isn't implemented, so will remove it form the readme
