### ISSUE TITLE
Support for GoogleAuth in TargetEndpoint

### ISSUE THREAD

**Issue by ssvaidyanathan** [apigee/apigee-templater#14]
Feature to customize the target endpoint with GoogleAuth

**Comment by tyayers** [comment]
Thanks for the feature suggestion, added in latest version 2.3.0, see example input5.cloudrun.json as described here: https://github.com/apigee/apigee-templater#examples

**Comment by ssvaidyanathan** [comment]
can we also somehow include `useTargetUrl` config as well so that it picks it from the Target Server?

**Comment by ssvaidyanathan** [comment]
I realized that this util does not support Target server.. Do we add that as a feature? I can open a GH issue

**Comment by ssvaidyanathan** [comment]
should also drop a note under https://github.com/apigee/apigee-templater?tab=readme-ov-file#apigee-features-covered

**Comment by tyayers** [comment]
Great suggestions, added the issues and features, along with some more fixes, see latest 2.4.0 version and updated readme.
