### ISSUE TITLE
Examples for adding Fault Rule and Post Client Flow, Properties as a File

### ISSUE THREAD

**Issue by RamShoban01** [apigee/apigee-templater#20]
Any examples for adding the policies in Fault Rule and Post Client Flow.
It will be helpful if we can configure to add the properties file to the proxy.

**Comment by tyayers** [comment]
Added a new example of PostClientFlow with MessageLogging policy, see updated Readme and test file. Working on testing Faults and adding property files...

**Comment by tyayers** [comment]
Properties and fault rules all possible now, test latest version and see examples on how to configure.
